/**
 * Song Model Definitions
 *
 * This file defines the data structures for songs in the application.
 * It contains three main interfaces:
 * - SongSummary: Contains basic information for list views
 * - SongCreate: Used for creating new songs without an ID
 * - Song: Full song details including ID and all properties
 *
 * @file
 * @module models/Song
 */

/**
 * SongSummary interface
 *
 * Represents the minimal information needed for displaying songs in lists,
 * tables, or summary views. Used primarily in paginated data displays.
 *
 * @interface SongSummary
 */
export interface SongSummary {
  /** Unique identifier for the song */
  id: string

  /** Title of the song */
  titre: string

  /** Artist/performer name */
  auteur: string

  /** Country of origin */
  pays: string

  /** Geographical region label (more specific than country) */
  region_geographique_libelle: string

  /** Language of the song lyrics */
  langue: string
}

/**
 * SongCreate interface
 *
 * Contains all fields needed for creating a new song, excluding the ID
 * which will be generated by the database. Includes both required and
 * optional properties.
 *
 * @interface SongCreate
 * @extends {Omit<SongSummary, 'id'>}
 */
export interface SongCreate extends Omit<SongSummary, 'id'> {
  /** Composer name (may differ from performer) */
  compositeur: string

  /** Full lyrics text of the song */
  paroles: string

  /** Category or genre of the song (e.g., "Folk", "Traditional") */
  type_de_chanson?: string

  /** Region code/identifier */
  region: string

  /** List of all performers/interpreters of the song */
  interpretes?: string[]

  /** Album name where the song was published */
  album?: string

  /** Thematic classification of the song */
  theme: string

  /** Historical background and context information */
  contexte_historique?: string

  /** Additional descriptive text about the song */
  description?: string

  /** Web links related to the song (comma or semicolon separated) */
  urls?: string

  /** Links to audio/video recordings of the song */
  urls_musique?: string

  /** Flag indicating if the song has been archived/removed from active display */
  archived: boolean
}

/**
 * Song interface - Complete song details
 *
 * Extends SongCreate to include the ID field. This is the complete
 * representation of a song in the system, containing all information
 * about a song including its identifier, lyrics, context, and media links.
 *
 * @interface Song
 * @extends {SongCreate}
 */
export interface Song extends SongCreate {
  /** Unique identifier for the song */
  id: string
}
